name: debug builds

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: sudo apt install -y build-essential cmake libjansson-dev nasm libz-dev clang
    - name: make
      run: make
  macos:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: brew install pkg-config cmake wget jansson go
    - name: make
      run: make
