name: flawfinder

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: flawfinder_scan
      uses: david-a-wheeler/flawfinder@2.0.19
      with:
        arguments: '--sarif ./native'
        output: 'flawfinder_results.sarif'
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        path: flawfinder_results.sarif   
    - name: Upload analysis results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{github.workspace}}/flawfinder_results.sarif
